language: ruby
sudo: required
dist: trusty
group: beta
cache: bundler
bundler_args: --without profile

notifications:
  irc: "irc.freenode.org#axlsx"
  email:
    recipients:
      - digital.ipseity@gmail.com
    on_success: always

matrix:
  include:
    - rvm: 2.1
    - rvm: 2.2.8
    - rvm: 2.3.5
    - rvm: 2.4.2
    - rvm: rbx-3
    - rvm: jruby-19mode
    - rvm: jruby-9.2.0.0
    - rvm: ruby-head
    - rvm: jruby-head
  allow_failures:
    - rvm: rbx-3
    - rvm: ruby-head
    - rvm: jruby-9.2.0.0
    - rvm: jruby-head

env:
  global:
    - JRUBY_OPTS="-Xcli.debug=true --debug"

# https://github.com/jruby/jruby/wiki/FAQs#why-is-jruby-so-slow-to-install-via-rvm
# https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-with-the-APT-Addon
addons:
  apt:
    packages:
    - haveged
