language: ruby
sudo: required
dist: trusty
group: beta
cache: bundler
bundler_args: --without profile
  
notifications:
  irc: "irc.freenode.org#axlsx"
  email:
    recipients:
      - digital.ipseity@gmail.com
    on_success: always

matrix:
  include:
    - rvm: 2.1
    - rvm: 2.2.7
    - rvm: 2.3.4
    - rvm: 2.0.0
    - rvm: 2.4.1
    - rvm: rbx-3
    - rvm: jruby-19mode
      env: JRUBY_OPTS="-Xcli.debug=true --debug"
    - rvm: jruby-9.1.8.0
      env: JRUBY_OPTS="-Xcli.debug=true --debug"
    - rvm: ruby-head
    - rvm: jruby-head
      env: JRUBY_OPTS="-Xcli.debug=true --debug"
  allow_failures:
    - rvm: rbx-3
    - rvm: ruby-head
    - rvm: jruby-9.1.8.0
    - rvm: jruby-head

# https://github.com/jruby/jruby/wiki/FAQs#why-is-jruby-so-slow-to-install-via-rvm
# https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-with-the-APT-Addon
addons:
  apt:
    packages:
    - haveged
